### PR TITLE
Require Ueberauth 0.7 and implement its CSRF protection

### PR DESCRIPTION
**Pull request by arjan**
This update makes Facebook login work again with the newest ueberauth

### CODE REVIEW

**Comment by yordis** [comment]
Thank you so much!

**Comment by njwest** [comment]
Is this change going to be published to Hex.pm soon?

**Comment by yordis** [comment]
@njwest I need @doomspork with the HEX API Token in the CI environment

**Comment by nbw** [comment]
@arjan @yordis I was the one that added the documentation for that state param. I'm totally on board with the new CSRF changes in 0.7, but I'm wondering how does one pass state now? Is that still possible? Apologies if I've missed something obvious. I've been reading through the original issue [#135](https://github.com/ueberauth/ueberauth/issues/135) [CSRF PR](https://github.com/ueberauth/ueberauth/pull/136/files), and this PR. 

I use the state param to pass a few things I need for later.

And thanks arjan for the PR.

**Comment by yordis** [comment]
@nbw it seems that we need to give people control over the `state` value, we need to fix `Ueberauth` itself for that.

Would you mind opening an issue there and ping me?

**Pull request merged**
