### PR TITLE
Feature/improved docs

### PR DESCRIPTION
**Pull request by nbw**
# Documentation improvements

# Add state (and other options)

I've recently been working on an app with Facebook login and having been sifting through their docs. I thought it would be worthwhile to add notes about how to pass state since it took me a while to find it in Facebook's docs.

1. Mention Call options in the README docs
2. Give an example of passing state

Screenshot 2021-04-12 at 22 54 31

Screenshot 2021-04-12 at 22 27 19

## 3. Updated Ex Doc

An error would occur when updating the docs. Updating Ex Doc was required to fix it.

Screenshot 2021-04-12 at 22 24 45

## 4. Linting and formatting

- Linter removed a few extra spaces in the README
- Ran mix format on `mix.exs`

### CODE REVIEW

**Comment by doomspork** [comment]
Thank you @nbw! This is great. We're currently working on a Ueberauth PR for state support so I'd like to give those involved in that an opportunity to comment here if need be.

Other PR: https://github.com/ueberauth/ueberauth/pull/136

**Comment by Hanspagh** [comment]
This looks good indeed, but we might need to wait for #136 to finish

**Comment by nbw** [comment]
I was just looking back at this PR to remind myself how passing state works again and it seems this might be mergeable now.

**Comment by Hanspagh** [comment]
@nbw Would mind to fix the conflict, then we can merge :D

**Comment by nbw** [comment]
@Hanspagh I merged master, but to resolve the lock file I regenerated it. I've noticed that it's updated a number of dependancies. If this is an issue and you'd prefer the mix.lock from master instead then let me know.

**Comment by Hanspagh** [comment]
I just made sure to undo all the changes to mix.lock since we already ex_doc at version 24.2.

**Review by Hanspagh — APPROVED** [review]
Thank you for your work 👍

**Pull request merged**
