### PR TITLE
Add display type to facebook oauth string to support popup

### PR DESCRIPTION
**Pull request by aphillipo**
It looks better in a part of my app if I use the display=popup parameter for the request url... 

Does it need a test?

### CODE REVIEW

**Comment by doomspork** [comment]
Thank you @aphillipo!  Let me look this over and let you know if I've got any feedback.

**Comment by aphillipo** [comment]
To be honest I'd love to be able to configure this per route (I have a popup and website that needs to be logged into) - any idea how that could be done?  Thanks!

**Comment by doomspork** [comment]
Sorry for the delay @aphillipo!  I'm not sure about a per-route configuration but that's a good question.  @hassox any thoughts on per-route ueberauth config?

**Comment by aphillipo** [comment]
Any luck with this?

**Comment by doomspork** [comment]
Howdy @aphillipo!  @hassox just returned from a much overdue vacation so he is playing catch-up with these different issues. 😀

**Comment by ben-ic** [comment]
Any updates on this?

**Comment by ben-ic** [comment]
Hi all, 

Any update on this?

**Comment by doomspork** [comment]
@ben-ic no updates that I am aware of.  I don't think @hassox (or myself) have had much time to investigate per-route configurations.

If this change as-is is sufficient we can release it.

**Comment by aphillipo** [comment]
Feel free to merge it - I think it's okay 👍🏻😀

**Comment by doomspork** [comment]
Thank you @aphillipo 👍

**Comment by douglascorrea** [comment]
@aphillipo do you have an example this working as a popup with javascript? My doubt is how to close the popup and continue the flow when it receives the callback. I'm doing something using `window.opener.` but I don't know if that is the best way to do it.

**Comment by aphillipo** [comment]
Hey douglas, in another thread people are suggesting packing a path into the state parameter which seems okay.  However, I'm using the session to handle this which might be bad.

**Comment by aphillipo** [comment]
I think this should be supported by the library maybe?

**Pull request merged**
