### PR TITLE
Add TravisCI and Dogma

### PR DESCRIPTION
**Pull request by doomspork**
RFC @hassox / @scrogson — Introduce Dogma, resolve current violations, and add TravisCI config.
#8 should probably get merged first.

### CODE REVIEW

**Comment by doomspork** [comment]
Should we update the README to include badges for the Hex Version and TravisCI build?

**Comment by doomspork** [comment]
Tests are failing for Elixir 1.0.5 because of the mix config.  Do we want to bother supporting 1.0?

**Comment by hassox** [comment]
I don't think 1.0.5 is worth it mate.

**Comment by doomspork** [comment]
@hassox I dropped 1.0.5 from the TravisCI config.  This should be good to go unless you have any feedback.

**Comment by hassox** [comment]
All LGTM mate! :+1:

**Pull request merged**
