### PR TITLE
Locale support

### LINKED ISSUE #10: fetch_user/2, inject locale param
Facebook has your name not only written in English(alphabet), but in language-specific name such as Umlaut, Japanese kanji, etc(I attache the snapshots, just in case).

You can get the language-specific name with `https://graph.facebook.com/me?locale=ja_JP&access_token=xxxxxx`. Is it possible to specify locale when you fetch user data?(maybe injecting it in fetch_user/2, path parameter)

facebook1

facebook2

### PR DESCRIPTION
**Pull request by doomspork**
RFC @hassox & @hykw — This should solve the issue in #10 by adding locale to the `/me` query string.  Thoughts, questions, and feedback welcome :grinning: 

Closes #10

### CODE REVIEW

**Comment by hassox** [comment]
I think it LGTM. @hykw can you confirm?

**Comment by hykw** [comment]
@hassox Yes! With `locale: "ja_JP"` in config, it worked perfectly. I was able to retrieve the data in ja_JP locale! Thank you.

**Comment by doomspork** [comment]
:tada:

If this looks good to you @hassox we can merge and release a new version.

**Comment by hassox** [comment]
@doomspork :shipit:

**Comment by doomspork** [comment]
@hykw this has been released as `0.3.1`.  Thanks for your help :+1:

**Comment by hykw** [comment]
@doomspork Good for you!

**Pull request merged**
